#!/bin/bash
# Generate the Api Reference using pydoc

cd ${0%/*}

# cleanup first
rm -f *.txt
rm -f *.html
rm -f *.pyc
rm -f *.py

# prepare packages
for d in iz_tools hypercore generator parser; do
  [ -d $d ] && rm -rf $d
  mkdir -p $d;
  cp ../../lib/$d/*.py $d/
  [ -f $d/setup.py ] && rm $d/setup.py
done

# get the code here
cp ../../HyperSQL.py .
cp ../../lib/*.py .
cp ../../hypersql.css .
[ -f test*.py ] && rm test*.py

# Generate the apidoc
for file in *.py iz_tools/*.py hypercore/*.py generator/*.py parser/*.py; do
  pydoc ./$file >${file%.py}.txt
  pydoc -w ./$file
done

# cleanup
rm -f __init__.html
rm -f *.py*
for d in iz_tools hypercore generator parser; do
  rm -rf $d
done

# Generate an index
echo '<HTML><HEAD>
  <TITLE>HyperSQL Api Reference</TITLE>
  <LINK REL="stylesheet" TYPE="text/css" HREF="hypersql.css">
</HEAD><BODY>
<H1>HyperSQL Api Reference</H1>
<P>Api References are available for the following modules:</P>
<UL>
' > index.html
for file in *.html; do
  echo "  <LI><A HREF='${file}'>${file%.html}</A></LI>" >> index.html
done
echo '</UL>
</BODY></HTML>' >> index.html
echo generated index.html
